USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/samsung/ivoryss/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := bcm21654
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a
TARGET_CPU_VARIANT := cortex-a9
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := ivoryss

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x82000000
BOARD_KERNEL_PAGESIZE := 4096

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00800000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00800000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x38000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x8547BC00
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/samsung/ivoryss/kernel
TARGET_KERNEL_SOURCE := kernel/samsung/ivoryss
TARGET_KERNEL_CONFIG := cyanogenmod_ivoryss_defconfig

BOARD_HAS_NO_SELECT_BUTTON := true
